name: "ubuntu ansible packages CI workflow"


on:
  push:
    branches: [ test ]

jobs:

  # ubuntu-1604-job:
  #   name: "osquery on ubuntu-16.04"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh   

  # ubuntu-1804-job:
  #   name: "osquery onubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh   

  # ubuntu-2004-job:
  #   name: "osquery on ubuntu-20.04"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh        

  ubuntu-latest-snmpv3-playbook:
    name: "snmpv3 ansible playbook on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "build virtualenv ansible "
      run: sudo make virtualenv-ansible     
    - name: "run snmp v3 playbook"
      run: |
        ansible all -i "localhost," -c local -m shell -a 'hostnamectl status'
        # cat /etc/ansible/hosts #/etc/ansible/hosts: No such file or directory
        ansible-playbook playbooks/localhost_playbook.yml --check #dry-run mode
        ansible -m debug -a 'var=hostvars' localhost        
        ansible-inventory --inventory-file=inventory --list
        ansible-inventory --inventory-file=inventory --graph
        ansible-inventory --inventory-file=inventory --host localhost
        ansible-playbook playbooks/localhost_playbook.yml --check    
        ansible-playbook playbooks/localhost_playbook.yml --tags "deploy-snmp-v3"

     
  ubuntu-latest-jenkins-playbook:
    name: "jenkins ansible playbook on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "build virtualenv ansible "
      run: sudo make virtualenv-ansible     
    - name: "run jenkins playbook"
      run: |
        ansible-galaxy install -r playbooks/requirements.yml
        ansible-playbook playbooks/localhost_playbook_jenkins.yml --check   